#!/bin/bash

PORT=12345
echo "Serveur TCP lancé sur le port $PORT..."

while true; do
nc -l localhost "$PORT" | while read commande; do
DATE=$(date)
echo "1+2" | bc

echo "Connexion le : $DATE"
echo "Bienvenue sur le serveur TCP !"

echo "Commande reçue : $commande"

resultat=$(eval "$commande" 2>&1) # Exécution + capture des erreurs
echo "$resultat"
done
echo "Client déconnecté..."
done
