#!/bin/bash

PORT=12345
echo "Serveur TCP lancé sur le port $PORT..."

while true; do
coproc nc -l localhost "$PORT"

DATE=$(date)
echo "Connexion le : $DATE" >&"${COPROC[1]}"
echo "Bienvenue sur le serveur TCP !" >&"${COPROC[1]}"

while read -r commande <&"${COPROC[0]}"; do
echo "Commande reçue : $commande" >&"${COPROC[1]}"
resultat=$(eval "$commande" 2>&1)
echo "$resultat" >&"${COPROC[1]}"
done

echo "Client déconnecté..."
done
